---
# tasks file for wordpress
 
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip

- name: Unzip WordPress
  unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no

- name: Copy WordPress files
  command: cp -a /tmp/wordpress/. /var/www/html
   creates=/var/www/html/wp-settings.php
